### ISSUE TITLE
Where the 'BytesBuilder' in zstd with the latest version?

### ISSUE THREAD

**Issue by isong0623** [instantiations/es_compression#21]

**Comment by isong0623** [comment]
Compiler message:
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/filters.dart:174:20: Error: Type 'BytesBuilder' not found.
  int _flush(final BytesBuilder bytesBuilder) {
                   ^^^^^^^^^^^^
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/filters.dart:184:23: Error: Type 'BytesBuilder' not found.
  int _finalize(final BytesBuilder bytesBuilder) {
                      ^^^^^^^^^^^^
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/filters.dart:193:13: Error: Type 'BytesBuilder' not found.
      final BytesBuilder bytesBuilder, int Function(CB outputBuffer) op) {
            ^^^^^^^^^^^^
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/sinks.dart:114:9: Error: Type 'BytesBuilder' not found.
  final BytesBuilder builder = BytesBuilder(copy: false);
        ^^^^^^^^^^^^
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/filters.dart:129:21: Error: The method 'BytesBuilder' isn't defined for the class 'CodecFilter<P, CB>'.
 - 'CodecFilter' is from 'package:es_compression/src/framework/filters.dart' ('/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/filters.dart').
Try correcting the name to the name of an existing method, or defining a method named 'BytesBuilder'.
    final builder = BytesBuilder(copy: false);
                    ^^^^^^^^^^^^
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/filters.dart:174:20: Error: 'BytesBuilder' isn't a type.
  int _flush(final BytesBuilder bytesBuilder) {
                   ^^^^^^^^^^^^
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/filters.dart:184:23: Error: 'BytesBuilder' isn't a type.
  int _finalize(final BytesBuilder bytesBuilder) {
                      ^^^^^^^^^^^^
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/filters.dart:193:13: Error: 'BytesBuilder' isn't a type.
      final BytesBuilder bytesBuilder, int Function(CB outputBuffer) op) {
            ^^^^^^^^^^^^
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/sinks.dart:114:9: Error: 'BytesBuilder' isn't a type.
  final BytesBuilder builder = BytesBuilder(copy: false);
        ^^^^^^^^^^^^
/C:/Users/Isidore/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/es_compression-0.9.9/lib/src/framework/sinks.dart:114:32: Error: Method not found: 'BytesBuilder'.
  final BytesBuilder builder = BytesBuilder(copy: false);
                               ^^^^^^^^^^^^
dart:async/stream_controller.dart 609:43                       _StreamController.addError
dart:async/stream_controller.dart 877:13                       _StreamSinkWrapper.addError
package:stream_channel/src/guarantee_channel.dart 144:14       _GuaranteeSink._addError
package:stream_channel/src/guarantee_channel.dart 135:5        _GuaranteeSink.addError
package:flutter_tools/src/test/flutter_platform.dart 454:27    FlutterPlatform._startTest
===== asynchronous gap ===========================
dart:async/zone.dart 1109:19                                   _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 79:23                        _asyncThenWrapperHelper
package:flutter_tools/src/test/flutter_platform.dart 359:36    FlutterPlatform.loadChannel
package:flutter_tools/src/test/flutter_platform.dart 312:46    FlutterPlatform.load
package:test_core/src/runner/loader.dart 232:38                Loader.loadFile.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1109:19                                   _CustomZone.registerUnaryCallback
dart:async-patch/async_patch.dart 79:23                        _asyncThenWrapperHelper
package:test_core/src/runner/loader.dart                       Loader.loadFile.<fn>
package:test_core/src/runner/load_suite.dart 98:31             new LoadSuite.<fn>.<fn>
package:test_core/src/runner/load_suite.dart 108:8             new LoadSuite.<fn>
package:test_api/src/backend/invoker.dart 400:30               Invoker._onRun.<fn>.<fn>.<fn>.<fn>
dart:async/future.dart 176:37                                  new Future.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1180:38                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
package:stack_trace/src/stack_zone_specification.dart 209:15   StackZoneSpecification._run
package:stack_trace/src/stack_zone_specification.dart 119:48   StackZoneSpecification._registerCallback.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1003:23                                   _CustomZone.bindCallback.<fn>
dart:async-patch/timer_patch.dart 23:15                        Timer._createTimer.<fn>
dart:isolate-patch/timer_impl.dart 398:19                      _Timer._runTimers
dart:isolate-patch/timer_impl.dart 429:5                       _Timer._handleMessage
dart:isolate-patch/isolate_patch.dart 168:12                   _RawReceivePortImpl._handleMessage
===== asynchronous gap ===========================
dart:async/zone.dart 1101:19                                   _CustomZone.registerCallback
dart:async/zone.dart 1018:22                                   _CustomZone.bindCallbackGuarded
dart:async/timer.dart 54:45                                    new Timer
dart:async/timer.dart 91:9                                     Timer.run
dart:async/future.dart 174:11                                  new Future
package:test_api/src/backend/invoker.dart 399:21               Invoker._onRun.<fn>.<fn>.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1619:10                                   _runZoned
dart:async/zone.dart 1539:10                                   runZoned
package:test_api/src/backend/invoker.dart 387:9                Invoker._onRun.<fn>.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1619:10                                   _runZoned
dart:async/zone.dart 1539:10                                   runZoned
package:test_api/src/backend/invoker.dart 148:7                Invoker.guard
package:test_api/src/backend/invoker.dart 436:15               Invoker._guardIfGuarded
package:test_api/src/backend/invoker.dart 386:7                Invoker._onRun.<fn>
package:stack_trace/src/chain.dart 101:24                      Chain.capture.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 1619:10                                   _runZoned
dart:async/zone.dart 1539:10                                   runZoned
package:stack_trace/src/chain.dart 99:12                       Chain.capture
package:test_api/src/backend/invoker.dart 385:11               Invoker._onRun
package:test_api/src/backend/live_test_controller.dart 197:11  LiveTestController._run
package:test_api/src/backend/live_test_controller.dart 50:37   _LiveTest.run
dart:async/future.dart 202:37                                  new Future.microtask.<fn>
dart:async/zone.dart 1180:38                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
dart:async/zone.dart 1184:13                                   _rootRun
dart:async/zone.dart 1077:19                                   _CustomZone.run
dart:async/zone.dart 979:7                                     _CustomZone.runGuarded
dart:async/zone.dart 1019:23                                   _CustomZone.bindCallbackGuarded.<fn>
dart:async/schedule_microtask.dart 43:21                       _microtaskLoop
dart:async/schedule_microtask.dart 52:5                        _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 118:13                   _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 169:5                    _RawReceivePortImpl._handleMessage

Failed to load "E:\My_WorkSpace\Dreaming.LotteryApp\test\widget_test.dart":
Compilation failed
Test: E:\My_WorkSpace\Dreaming.LotteryApp\test\widget_test.dart
Shell: E:\My_Developments\Android\SDK\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe

**Comment by isong0623** [comment]
i fixed this problem.
thx,you are right.
i modified "src/framework/filters.dart" and "src/framework/sinks.dart" with new line "import 'dart:io'".
the 'git version' works fine,and can decode with java (com.github.luben.zstd.Zstd),
but the 'flutter version' meet new problem 
**dlopen failed: library "eszstd-android64.so" not found** in android phone
**dlopen failed: library "eszstd-android32.so" not found** in AVD

Debug service listening on ws://127.0.0.1:63729/Y_nAFb8syVI=/ws
Syncing files to device M1822...
I/OpenGLRenderer(25508): Initialized EGL, version 1.4
I/TextToSpeech(25508): Connected to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
I/TextToSpeech(25508): Set up connection to ComponentInfo{com.svox.pico/com.svox.pico.PicoService}
E/TTS     (25508): getDefaultLocale: Attempt to invoke virtual method 'java.util.Locale android.speech.tts.Voice.getLocale()' on a null object reference
E/flutter (25508): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "eszstd-android64.so" not found)
E/flutter (25508): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
E/flutter (25508): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter (25508): #2      OpenLibraryStrategy.open (package:es_compression/src/framework/native/library/open_library_strategy.dart:37:29)
E/flutter (25508): #3      OpenViaOsResolutionStrategy.openFor (package:es_compression/src/framework/native/library/os_resolution_strategy.dart:26:12)
E/flutter (25508): #4      OpenLibrary.openLibrary (package:es_compression/src/framework/native/library/open_library.dart:43:32)
E/flutter (25508): #5      new ZstdLibrary._ (package:es_compression/src/zstd/ffi/library.dart:56:20)
E/flutter (25508): #6      ZstdLibrary._instance (package:es_compression/src/zstd/ffi/library.dart:34:52)
E/flutter (25508): #7      ZstdLibrary._instance (package:es_compression/src/zstd/ffi/library.dart:34:28)
E/flutter (25508): #8      new ZstdLibrary (package:es_compression/src/zstd/ffi/library.dart:50:12)
E/flutter (25508): #9      new ZstdDispatcher (package:es_compression/src/zstd/ffi/dispatcher.dart:47:15)
E/flutter (25508): #10     new ZstdDecompressFilter (package:es_compression/src/zstd/ffi/decompress_filter.dart:18:38)
E/flutter (25508): #11     _makeZstdCompressFilter (package:es_compression/src/zstd/decoder.dart:61:10)
E/flutter (25508): #12     new _ZstdDecoderSink._ (package:es_compression/src/zstd/decoder.dart:51:13)
E/flutter (25508): #13     ZstdDecoder.startChunkedConversion (package:es_compression/src/zstd/decoder.dart:42:29)
E/flutter (25508): #14     CodecConverter.convert (package:es_compression/src/framework/converters.dart:20:7)
E/flutter (25508): #15     Codec.decode (dart:convert/codec.dart:28:34)
E/flutter (25508): #16     main (package:Lottery/main.dart:41:35)
E/flutter (25508): #17     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (25508): #18     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (25508): #19     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (25508): #20     _runZoned (dart:async/zone.dart:1619:10)
E/flutter (25508): #21     runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (25508): #22     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (25508): #23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (25508): #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by isong0623** [comment]
I generate the so lib for android.
See https://github.com/isong0623/android_lib_es_compression0_9_9[https://github.com/isong0623/android_lib_es_compression0_9_9](url)
