### ISSUE TITLE
Failed to load dynamic library 'esbrotli-android64.so': dlopen failed: library "esbrotli-android64.so not found

### ISSUE THREAD

**Issue by Dewsworld** [instantiations/es_compression#25]
```
[ +129 ms] E/flutter (29516): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'esbrotli-android64.so': dlopen failed: library "esbrotli-android64.so" not found
[        ] E/flutter (29516): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
[        ] E/flutter (29516): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
[        ] E/flutter (29516): #2      OpenLibraryStrategy.open (package:es_compression/src/framework/native/library/open_library_strategy.dart:35:29)
[        ] E/flutter (29516): #3      OpenViaOsResolutionStrategy.openFor (package:es_compression/src/framework/native/library/os_resolution_strategy.dart:26:12)
[        ] E/flutter (29516): #4      OpenLibrary.openLibrary (package:es_compression/src/framework/native/library/open_library.dart:43:32)
[        ] E/flutter (29516): #5      new BrotliLibrary._ (package:es_compression/src/brotli/ffi/library.dart:58:20)
[        ] E/flutter (29516): #6      BrotliLibrary._instance (package:es_compression/src/brotli/ffi/library.dart:36:21)
[        ] E/flutter (29516): #7      BrotliLibrary._instance (package:es_compression/src/brotli/ffi/library.dart)
[        ] E/flutter (29516): #8      new BrotliLibrary (package:es_compression/src/brotli/ffi/library.dart:52:12)
[        ] E/flutter (29516): #9      new BrotliDispatcher (package:es_compression/src/brotli/ffi/dispatcher.dart:65:34)
[        ] E/flutter (29516): #10     new BrotliCompressFilter (package:es_compression/src/brotli/ffi/compress_filter.dart:20:40)
[        ] E/flutter (29516): #11     _makeBrotliCompressFilter (package:es_compression/src/brotli/encoder.dart:179:10)
[        ] E/flutter (29516): #12     new _BrotliEncoderSink._ (package:es_compression/src/brotli/encoder.dart:148:13)
[        ] E/flutter (29516): #13     BrotliEncoder.startChunkedConversion (package:es_compression/src/brotli/encoder.dart:115:31)
[        ] E/flutter (29516): #14     CodecConverter.convert (package:es_compression/src/framework/converters.dart:20:7)
[        ] E/flutter (29516): #15     Codec.encode (dart:convert/codec.dart:21:32)
[        ] E/flutter (29516): #16     _LbWhiteboardState.initState.<anonymous closure> (package:pathon/home/ui/whiteboard_widget.dart:36:31)
[        ] E/flutter (29516): #17     _rootRunUnary (dart:async/zone.dart:1362:47)
[        ] E/flutter (29516): #18     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
[        ] E/flutter (29516): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
[        ] E/flutter (29516): #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
[        ] E/flutter (29516): #21     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
[        ] E/flutter (29516): #22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
[        ] E/flutter (29516): #23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
[        ] E/flutter (29516): #24     _rootRun (dart:async/zone.dart:1346:47)
[        ] E/flutter (29516): #25     _CustomZone.run (dart:async/zone.dart:1258:19)
[        ] E/flutter (29516): #26     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
[        ] E/flutter (29516): #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
[        ] E/flutter (29516): #28     _rootRun (dart:async/zone.dart:1354:13)
[        ] E/flutter (29516): #29     _CustomZone.run (dart:async/zone.dart:1258:19)
[        ] E/flutter (29516): #30     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
[        ] E/flutter (29516): #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
[        ] E/flutter (29516): #32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
[        ] E/flutter (29516): #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
I have installed it in pubscpec.yaml 
  es_compression: ^2.0.2

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Android Studio
[✓] Connected device (2 available)

• No issues found!

**Comment by sethloco** [comment]
Hello,

I just want to make sure you aware that this library provides "FFI implementations for Brotli, Lz4, Zstd (Zstandard) with **ready-to-use prebuilt binaries for Win/Linux/Mac**."

Have you built the brotli library for android?  By default, it will look for a library named esbrotli-android64.so, but this is configurable in a number of ways.  @see [Deployment](https://github.com/instantiations/es_compression#deployment) section of readme for some different options.

If you have built the library, but are having a problem resolving it, please let me know and I'll try and help.

If you have **not** build the library, I would review issue #20 , as a contributor provided an example on how to build libraries for android.  It has been included in our examples [here](https://github.com/instantiations/es_compression/tree/master/example/android_jniLibs_generate)

- Seth

**Comment by sethloco** [comment]
Hello,

Let me know if you have any further questions on this. I’ll close the case in a few days otherwise.

**Comment by sethloco** [comment]
Closing issue...no response
